name: Build and Deploy

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  deploy:
    name: Build and Deploy
    needs: test


    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    with:
      deploy_environments: '["sbx","dev"]'
